# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'CommonWheels' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # use_modular_headers！

  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Moya-ObjectMapper/RxSwift'

end
